### ISSUE TITLE
Error: "Uploaded file does not contain any component definition files."

### ISSUE THREAD

**Issue by OfficialDarkComet** [shreyashsaitwal/recast#1]
![Screenshot 2021-07-15 154407](https://user-images.githubusercontent.com/34902421/125855214-655dd331-b937-4c2c-8f50-839356c7605c.png)

**Comment by shreyashsaitwal** [comment]
Thanks for reporting, I'm investigating the issue. Will release a fix soon.

**Comment by shreyashsaitwal** [comment]
Fixed by [v0.1.1](https://github.com/shreyashsaitwal/recast/releases/tag/v0.1.1)
